Models/Project.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace TheBugTracker.Models
{
    public class Project
    {
        private DateTime _created;
        private DateTime _startdate;
        private DateTime _enddate;
        public int Id { get; set; }
        public int CompanyId { get; set; }
        [Required]
        [StringLength(200, ErrorMessage = "The {0} must be at most {1} characters long.")]
        public string? Name { get; set; }
        [Required]
        public string? Description { get; set; }
        public DateTime Created
        {
            get => _created;
            set => _created = value.ToUniversalTime();
        }
        public DateTime StartDate
        {
            get => _startdate;
            set => _startdate = value.ToUniversalTime();
        }
        public DateTime EndDate
        {
            get => _enddate;
            set => _enddate = value.ToUniversalTime();
        }
        public int ProjectPriorityId { get; set; }

        //ImageFormFile(IFormFile)-avatar img
        public byte[]? ImageFileData { get; set; }

        //ImageFileData(byte[])
        public string? ImageFileType { get; set; }

        [NotMapped]
        //ImageFileType(string)-it's like the envelope the image in, so we don't store it
        public IFormFile? ImageFormFile { get; set; }

        public bool Archived { get; set; }

        //Nav Prop
        public virtual Company? Company { get; set; }
        public virtual ProjectPriority? ProjectPriority { get; set; }
        public virtual ICollection<BTUser> Members { get; set; } = new HashSet<BTUser>();

        public virtual ICollection<Ticket> Tickets { get; set; } = new HashSet<Ticket>();
    }
}

Models/ViewModels/AssignPMViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TheBugTracker.Models.ViewModels
{
    public class AssignPMViewModel
    {
        public int ProjectId { get; set; }
        public string? ProjectName { get; set; }
        public SelectList? PMList { get; set; }
        public string? PMId { get; set; }
    }
}

Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TheBugTracker.Data;
using TheBugTracker.Extensions;
using TheBugTracker.Models;
using TheBugTracker.Models.Enums;
using TheBugTracker.Models.ViewModels;
using TheBugTracker.Services.Interfaces;

namespace TheBugTracker.Controllers
{
    [Authorize]
    public class ProjectsController : BTBaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<BTUser> _userManager;
        private readonly IBTFileService _bTFileService;
        private readonly IBTTicketService _btTicketService;
        private readonly IBTProjectService _projectService;
        private readonly IBTRolesService _rolesService;

        public ProjectsController(ApplicationDbContext context, UserManager<BTUser> userManager, IBTFileService bTFileService, IBTTicketService btTicketService, IBTProjectService projectService, IBTRolesService rolesService)
        {
            _context = context;
            _userManager = userManager;
            _bTFileService = bTFileService;
            _btTicketService = btTicketService;
            _projectService = projectService;
            _rolesService = rolesService;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
            IEnumerable<Project> projects = await _projectService.GetAllProjectsByCompanyIdAsync(_companyId);
            return View(projects);
            
        }

		// GET: Projects/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			// Remember that the _context should not be used directly in the controller so....     

			// Edit the following code to use the service layer. 
			// Your goal is to return the 'project' from the databse
			// with the Id equal to the parameter passed in.               
			// This is the only modification necessary for this method/action.     

			var project = await _context.Projects
				.Include(p => p.Company)
                .Include(p=> p.Members)
				.Include(p => p.ProjectPriority)
                .Include(p=>p.Tickets)
                .ThenInclude(t=>t.History)
                .ThenInclude(th=>th.User)
				.FirstOrDefaultAsync(m => m.Id == id);

            ViewData["Tickets"] = await _btTicketService.GetTicketsByProjectIdAsync(project?.Id);


			if (project == null)
			{
				return NotFound();
			}

			return View(project);
		}

		// GET: Projects/Create
		public IActionResult Create()
        {

            int companyId = User.Identity!.GetCompanyId();
            ViewData["ProjectPriorityId"] = new SelectList(_context.ProjectPriorities, "Id", "Name");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,StartDate,EndDate,ProjectPriorityId,ImageFormFile,CompanyId")] Project project)
        {
            if (ModelState.IsValid)
            {
                if (project.ImageFormFile != null)
                {
                    // Create the Image Service
                    // 1. Convert file to byte array and assign to ImageDate
                    project.ImageFileData = await _bTFileService.ConvertFileToByteArrayAsync(project.ImageFormFile);
                    // 2. Assign the ImageType based on the choosen file
                    project.ImageFileType = project.ImageFormFile.ContentType;
                }

                project.Created = DateTime.Now;

                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", project.CompanyId);
            ViewData["ProjectPriorityId"] = new SelectList(_context.ProjectPriorities, "Id", "Id", project.ProjectPriorityId);
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Projects == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", project.CompanyId);
            ViewData["ProjectPriorityId"] = new SelectList(_context.ProjectPriorities, "Id", "Name", project.ProjectPriorityId);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CompanyId,Name,Description,Created,StartDate,EndDate,ProjectPriorityId,ImageFileData,ImageFileType,ImageFormFile,Archived")] Project project)
        {
            if (id != project.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                //Set the Image data if one has been choosen
                if (project.ImageFormFile != null)
                {
                    // Create the Image Service
                    // 1. Convert file to byte array and assign to ImageDate
                    project.ImageFileData = await _bTFileService.ConvertFileToByteArrayAsync(project.ImageFormFile);
                    // 2. Assign the ImageType based on the choosen file
                    project.ImageFileType = project.ImageFormFile.ContentType;
                }

                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", project.CompanyId);
            ViewData["ProjectPriorityId"] = new SelectList(_context.ProjectPriorities, "Id", "Id", project.ProjectPriorityId);
            return View(project);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AssignPM(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            Project? project = await _projectService.GetProjectByIdAsync(id, _companyId);

            if(project == null)
            {
                return NotFound();
            }

            //get list of PMs

            IEnumerable<BTUser> projectManagers = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.ProjectManager), _companyId);

            //gets us PM user if assigned

            BTUser? currentPM = await _projectService.GetProjectManagerAsync(id);

            AssignPMViewModel viewModel = new()
            {
                ProjectId = project.Id,
                    ProjectName = project.Name,
                    PMList = new SelectList(projectManagers, "Id", "FullName", currentPM?.Id),
                    PMId = currentPM?.Id
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignPM(AssignPMViewModel viewModel)
        {
            if(!string.IsNullOrEmpty(viewModel.PMId))
            {
                if (await _projectService.AddProjectManagerAsync(viewModel.PMId, viewModel.ProjectId))
                {
                    return RedirectToAction(nameof(Details), new { id = viewModel.ProjectId });
                }
                else
                {

                    ModelState.AddModelError("PMId", "Error assigning PM.");
                }
                //ModelState.AddModelError("PMId", "Error, No PM chosen, please choose a PM");
            }


            ModelState.AddModelError("PMId", "No Project Manager chosen. Please select a Project Manager.");
            IEnumerable<BTUser> projectManagers = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.ProjectManager), _companyId);

            //gets us PM user if assigned

            BTUser? currentPM = await _projectService.GetProjectManagerAsync(viewModel.ProjectId);
            viewModel.PMList = new SelectList(projectManagers, "Id", "FullName", currentPM.Id);
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AssignProjectMembers(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //getting a project back?
            Project? project = await _projectService.GetProjectByIdAsync(id, _companyId);

            if (project == null)
            {
                return NotFound();
            }
            List<BTUser> submitters = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.Submitter), _companyId);

Views/Projects/Archive.cshtml
@model TheBugTracker.Models.Project

@{
    ViewData["Title"] = "Archive";
}

<h1>Delete</h1>

<h3>Are you sure you want to archive this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageFileData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageFileType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Archived)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Archived)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPriority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPriority.Name)
        </dd>
    </dl>
    
    <form asp-action="Archive">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Archive" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Projects/AssignPM.cshtml
@model AssignPMViewModel
@using TheBugTracker.Models.ViewModels;
@{
    ViewData["Title"] = "Assign Project Manager";
}
<body class="dark">
    <!-- Preloader -->
    <div class="preloader">
        <div class="preloader-icon"></div>
        <span>Loading...</span>
    </div>
    <!-- begin::navigation -->
    <!-- end::navigation -->
    <!-- Content body -->
    <div class="content-body">
<div class="d-flex justify-content-center mt-5 flex-column align-items-center col-12">
    <h3 class="my-5">Assign Project Manager</h3>
    <div class="card">
        <div class="card-header">
            <div class="card-title">@Model.ProjectName</div>
        </div>
        <div class="card-body">
            <form asp-action="AssignPM" asp-controller="Projects" method="post" class="d-flex flex-column">
                <input type="hidden" asp-for="ProjectId" />
                <select asp-items="Model.PMList" asp-for="PMId">
                    <option value="">Unassigned</option>
                </select>
                <span asp-validation-for="PMId" class="text-danger"></span>
                <button type="submit" class="btn btn-primary my-3">Save</button>
                @*<a asp-action="Details" asp-route-id="@Model.ProjectId" class="btn btn-secondary">Cancel</a>*@
                <a asp-action="Index" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>


</body>
</html>

Views/Projects/AssignProjectMembers.cshtml
@model ProjectMembersViewModel
@using TheBugTracker.Models.ViewModels;
@{
    ViewData["Title"] = "Assign Project Members";
}
<div class="d-flex justify-content-center mt-5 flex-column align-items-center">
    <h3 class="my-5">Assign Project Members- Click and Drag</h3>
    <div class="card">
        <div class="card-header">
            <div class="card-title">@Model.Project!.Name</div>
        </div>
        <div class="card-body">
            <form asp-action="AssignProjectMembers" asp-controller="Projects" method="post" class="d-flex flex-column">
                <input type="hidden" asp-for="Project!.Id" />
                <select asp-items="Model.UsersList" asp-for="SelectedMembers" class="form-control" multiple required>
                </select>
                <span asp-validation-for="SelectedMembers" class="text-danger"></span>
                <button type="submit" class="btn btn-primary my-3">Save</button>
                <a asp-action="Details" asp-route-id="@Model.Project!.Id" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>

Views/Projects/Create.cshtml
@model TheBugTracker.Models.Project
@using Microsoft.AspNetCore.Identity;
@using TheBugTracker.Extensions; 

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CompanyId" value="@User.Identity!.GetCompanyId()" />
           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectPriorityId" class="control-label"></label>
                <select asp-for="ProjectPriorityId" class ="form-control" asp-items="ViewBag.ProjectPriorityId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ImageFormFile" class="control-label"></label>
                <input asp-for="ImageFormFile" class="form-control" />
                <span asp-validation-for="ImageFormFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Projects/Delete.cshtml
@model TheBugTracker.Models.Project

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageFileData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageFileType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Archived)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Archived)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPriority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectPriority.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Projects/Edit.cshtml
@model TheBugTracker.Models.Project

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Project</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="Created" />
            <input type="hidden" asp-for="ImageFileData" />
            <input type="hidden" asp-for="ImageFileType" />
            <input type="hidden" asp-for="CompanyId" />

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label">Start Date</label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label">End Date</label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectPriorityId" class="control-label">Project Priority</label>
                <select asp-for="ProjectPriorityId" class="form-control" asp-items="ViewBag.ProjectPriorityId"></select>
                <span asp-validation-for="ProjectPriorityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFormFile" class="control-label"></label>
                <input asp-for="ImageFormFile" class="form-control" accept=".png,.jpg,.jpeg,.gif" />
                <span asp-validation-for="ImageFormFile" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Archived" /> @Html.DisplayNameFor(model => model.Archived)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Projects/Index.cshtml
@using TheBugTracker.Models.Enums;
@using TheBugTracker.Services.Interfaces;
@model IEnumerable<TheBugTracker.Models.Project>
@inject IBTFileService _BTFileService

@{
    ViewData["Title"] = "Index";
}

@section Scripts{
<!-- Javascript -->
<script src="~/vendors/dataTable/datatables.min.js"></script>
<script>
    $("#myTable").DataTable({responsive: true})
</script>
}

<h1>Projects</h1>
@if(User.IsInRole(BTRoles.Admin.ToString()) || User.IsInRole(BTRoles.ProjectManager.ToString()))
{
    <p>
        <a class="btn btn-primary" asp-action="Create">Create New</a>
    </p>
}



<table id="myTable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                img
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Archived)
            </th>
           
            <th>
                @Html.DisplayNameFor(model => model.ProjectPriority)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @item.Created.ToString("g")
                </td>
                <td>
                    @item.StartDate.ToString("g")
                </td>
                <td>
                    @item.EndDate.ToString("g")
                </td>
                <td>
                    <img width="40" src="@_BTFileService.ConvertByteArrayToFile(@item?.ImageFileData!,@item?.ImageFileType!,DefaultImage.BTUserImage)" class="rounded mr-3" alt="Vase">
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Archived)
                </td>
                
                <td>
                    @Html.DisplayFor(modelItem => item.ProjectPriority.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="AssignPM" asp-route-id="@item.Id">Assign PM</a> |
                    <a asp-action="AssignProjectMembers" asp-route-id="@item.Id">Assign Project Members</a> |

                    @if (item.Archived == true)
                    {
                        <a asp-action="Restore" asp-route-id="@item.Id">Restore</a>
                    }
                    else
                    {
                        <a asp-action="Archive" asp-route-id="@item.Id">Archive</a>
                    }
                </td>
            </tr>
        }
        
    </tbody>
</table>

Views/Projects/Restore.cshtml
@model TheBugTracker.Models.Project

@{
    ViewData["Title"] = "Restore";
}

<h1>Delete</h1>

<h3>Are you sure you want to restore this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileData)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImageFileData)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageFileType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImageFileType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Archived)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Archived)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Company.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProjectPriority)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProjectPriority.Id)
        </dd>
    </dl>

    <form asp-action="Restore">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Restore" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>